### PR TITLE
Added MongoDB support

### PR DESCRIPTION
**Pull request by dixonwille**
This is in regards to #4 

Things to note
- Must have MongoDB installed and running
- must have a database with two different collections
  - One for wins and one for fails

All config values are environment variables. Which I updated in the DockerFile (Must use your own proper configs).

You can have a `.env` file that will be loaded on start so you don't have to set your environment before run locally.

Please critique it. This was the solution I came up with.

### CODE REVIEW

**Comment by msegoviadev** [comment]
Wow ! Ty for your time @dixonwille , I'll try to take time along the week to hands on this. I'll have to update the current infrastructure tu provide mongo inside the container.

Keep the contributions ! ;)

**Comment by dixonwille** [comment]
Mongo in Docker is not persistant... 
http://stackoverflow.com/questions/34753792/howto-persist-mongodb-data-of-a-running-docker-container-in-a-new-image
I would suggest running a separate instance outside of docker and point to it. If you are using AWS I would use AWS EBS

**Comment by msegoviadev** [comment]
Thanks for the suggestion dixon and also for the info on not persistance, as it really makes sense.
I guess the idea of writing mongodb data into a volume of the current host and being able to run a new container with the previous volume path is what best fits in my mind.
I'll try to make my way through this approach as AWS is not an option right now :) Really want to make the service as portable as posible to anybody who wants to contribute.

**Comment by dixonwille** [comment]
@MarcosSegovia sounds good. I was in the rut and could not figure out why my DB was not persisting and didn't want others to fall into that route.

**Comment by msegoviadev** [comment]
I'm merging into a feature branch since I get the docker working properly. Ty @dixonwille

**Comment by msegoviadev** [comment]
Hi @dixonwille I've fully merged your proposal after dockerizing the process and getting my hands dirty with the code.
Still things to get done:
- Normalize the `Entry` in the API as it would be our Primary Entity of the Domain, and has to be completely agnostic of the persistence system.
- Even though could run in separate containers and link application container with database container, still did not find a way to get the data persisted into a new container. When stop and resume data is still available. But I guess has to do with the inmutability. Anyway I'll find a way.

If you are interested in the code changes, let me know, we can discuss about it 👍

**Comment by dixonwille** [comment]
Saw the changes and makes since. I don't like messing with too many files in other people's repository. So I just like to get it working. Glad to see you pulled it apart as I try and do that with my projects as well. As for persisting you tried storing the db files to a volume through docker? use that same volume everytime you connect and you get persistence. The issue is when you go for a distributed system (AWS, Digital Ocean, Heroku for testing etc.). Then you would probably just want to stand up a DB outside of Docker in that case.

**Pull request merged**
